# Generated by Django 3.1.5 on 2021-01-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_registeredvehicles_vehicle_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredvehicles',
            name='towed_count',
        ),
    ]
