# Generated by Django 3.1.5 on 2021-01-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawEnforcementUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('address', models.TextField(default='')),
                ('pincode', models.CharField(default='', max_length=40)),
                ('password_recovery_key', models.CharField(default='', max_length=200)),
                ('activation_key', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='law_enforcement_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('address', models.TextField(default='')),
                ('pincode', models.CharField(default='', max_length=40)),
                ('password_recovery_key', models.CharField(default='', max_length=200)),
                ('activation_key', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
