# Generated by Django 3.1.5 on 2021-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=252)),
                ('email', models.CharField(default='', max_length=252)),
                ('subject', models.CharField(default='', max_length=400)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
