# Generated by Django 3.1.5 on 2021-01-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowedVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=200)),
                ('owner_email', models.CharField(default='', max_length=200)),
                ('owner_phone_no', models.CharField(default='', max_length=200)),
                ('vehicle_name', models.CharField(default='', max_length=200)),
                ('vehicle_type', models.CharField(default='', max_length=200)),
                ('towed_date', models.DateTimeField(default='')),
                ('fine_amount', models.PositiveIntegerField(default=0)),
                ('is_fine_paid', models.BooleanField(default=False)),
                ('is_vehicle_returned', models.BooleanField(default=False)),
                ('enforcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towed_company', to='accounts.lawenforcementusers')),
            ],
        ),
    ]
