# Generated by Django 3.1.5 on 2021-01-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcementcompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towedvehicles',
            name='vehicle_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='towedvehicles',
            name='towed_date',
            field=models.DateField(default=''),
        ),
    ]
